### ISSUE TITLE
UnicodeDecodeError during install

### ISSUE THREAD

**Issue by zoranzaric** [Apsu/infusion#1]
When I try to `pip install` infusion I get this error:

```
$ pip install https://github.com/Apsu/infusion
Downloading/unpacking https://github.com/Apsu/infusion
  Downloading infusion (unknown size): 8.2kB downloaded
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/home/foo/project/.virtualenv/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/foo/project/.virtualenv/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/foo/project/.virtualenv/lib/python2.7/site-packages/pip/req.py", line 1197, in prepare_files
    do_download,
  File "/home/foo/project/.virtualenv/lib/python2.7/site-packages/pip/req.py", line 1375, in unpack_url
    self.session,
  File "/home/foo/project/.virtualenv/lib/python2.7/site-packages/pip/download.py", line 582, in unpack_http_url
    unpack_file(temp_location, location, content_type, link)
  File "/home/foo/project/.virtualenv/lib/python2.7/site-packages/pip/util.py", line 627, in unpack_file
    and is_svn_page(file_contents(filename))):
  File "/home/foo/project/.virtualenv/lib/python2.7/site-packages/pip/util.py", line 210, in file_contents
    return fp.read().decode('utf-8')
  File "/home/foo/project/.virtualenv/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte
```

Python version is 2.7.5
pip version is 1.5.6

**Comment by onelson** [comment]
I'm guessing @Apsu didn't write this intending to support Python 2.x _and_ 3.x from the same code base, but I do know that he wrote this targeting Python 3.x. Maybe try and install from a Python 3 install?
